# Generated by Django 4.1.7 on 2023-03-26 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_number', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Outgoing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.IntegerField(unique=True)),
                ('date_dispatched', models.DateField()),
                ('document_type', models.CharField(choices=[('EM', 'Email'), ('LR', 'Letter'), ('OT', 'OTHER')], max_length=2)),
                ('sent_to', models.CharField(max_length=300)),
                ('subject', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('DP', 'Dispatched'), ('DL', 'Delivered'), ('RT', 'Returned')], max_length=2)),
                ('url', models.URLField(null=True)),
                ('dispatched_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='record_app.employees')),
                ('file_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record_app.files')),
            ],
        ),
        migrations.CreateModel(
            name='Incoming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.IntegerField(unique=True)),
                ('date_received', models.DateField()),
                ('document_type', models.CharField(choices=[('EM', 'Email'), ('LR', 'Letter'), ('OT', 'OTHER')], max_length=2)),
                ('received_from', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('FL', 'Filed'), ('IP', 'InProcess')], max_length=2, null=True)),
                ('url', models.URLField(null=True)),
                ('file_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record_app.files')),
                ('marked_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='record_app.employees')),
            ],
        ),
    ]
